"""Core infrastructure: configuration, constants, exceptions, logging."""

from picocloth_cli.core.config import CLIConfig, get_config, load_config, reload_config, save_config
from picocloth_cli.core.constants import (
    COMPACTION_ARCHIVE_DIR,
    COMPACTION_THRESHOLD_PERCENT,
    DEFAULT_CONTEXT_WINDOW,
    DEFAULT_HEARTBEAT_INTERVAL,
    DEFAULT_MAX_ITERATIONS,
    DEFAULT_MAX_TOKENS,
    DIGITAL_TWINS_DIR,
    DOCTRINE_DIR,
    FLEET_SERVER_PATH,
    FLEET_SHARED_DIR,
    INTENT_CONFIDENCE_THRESHOLD,
    MAX_SPAWN_DEPTH,
    NODE_PORTS,
    NODE_ROLES,
    NODES,
    PICOCLOTH_DIR,
    PROJECT_DIR,
    RUN_DIR,
    SHARED_DIR,
    SPAWN_COMPLEXITY_THRESHOLD,
    STATE_DIR,
)
from picocloth_cli.core.exceptions import (
    AgentError,
    AgentRegistryError,
    CompactionError,
    ConfigError,
    FleetError,
    IntentClassificationError,
    IntentError,
    IntentResolutionError,
    LockFileError,
    LowConfidenceError,
    MCPConnectionError,
    MemoryError,
    MemoryLayerError,
    MemorySliceError,
    NodeNotFoundError,
    NodeOfflineError,
    PicoClothError,
    SchemaValidationError,
    SpawnDepthExceededError,
    TaskQueueError,
)
from picocloth_cli.core.logging import CONSOLE, get_logger, setup_logging

__all__ = [
    # Config
    "CLIConfig",
    "get_config",
    "load_config",
    "reload_config",
    "save_config",
    # Constants
    "PICOCLOTH_DIR",
    "SHARED_DIR",
    "DOCTRINE_DIR",
    "PROJECT_DIR",
    "STATE_DIR",
    "RUN_DIR",
    "DIGITAL_TWINS_DIR",
    "COMPACTION_ARCHIVE_DIR",
    "FLEET_SERVER_PATH",
    "FLEET_SHARED_DIR",
    "NODES",
    "NODE_PORTS",
    "NODE_ROLES",
    "DEFAULT_CONTEXT_WINDOW",
    "DEFAULT_MAX_TOKENS",
    "DEFAULT_MAX_ITERATIONS",
    "DEFAULT_HEARTBEAT_INTERVAL",
    "INTENT_CONFIDENCE_THRESHOLD",
    "SPAWN_COMPLEXITY_THRESHOLD",
    "MAX_SPAWN_DEPTH",
    "COMPACTION_THRESHOLD_PERCENT",
    # Exceptions
    "PicoClothError",
    "FleetError",
    "NodeNotFoundError",
    "NodeOfflineError",
    "MCPConnectionError",
    "TaskQueueError",
    "IntentError",
    "IntentClassificationError",
    "IntentResolutionError",
    "LowConfidenceError",
    "AgentError",
    "SpawnDepthExceededError",
    "AgentRegistryError",
    "MemorySliceError",
    "MemoryError",
    "MemoryLayerError",
    "LockFileError",
    "CompactionError",
    "SchemaValidationError",
    "ConfigError",
    # Logging
    "CONSOLE",
    "get_logger",
    "setup_logging",
]
